// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBElsmr04m4H5GSg_ARLLmpgKFTgdA2jg0',
    appId: '1:1004167085921:web:e71598a5a95c4c1af2cf20',
    messagingSenderId: '1004167085921',
    projectId: 'pulchowkx-cb4e7',
    authDomain: 'pulchowkx-cb4e7.firebaseapp.com',
    storageBucket: 'pulchowkx-cb4e7.firebasestorage.app',
    measurementId: 'G-HTWPGXHX04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD5T4zU8xglu1Nb4Q6zTTGjJm0-M_st8o',
    appId: '1:1004167085921:android:9dcc374f888ba820f2cf20',
    messagingSenderId: '1004167085921',
    projectId: 'pulchowkx-cb4e7',
    storageBucket: 'pulchowkx-cb4e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUO95owZ3EzkaziLVmFkZp5eMSEWxfstY',
    appId: '1:1004167085921:ios:4ad05d772ac02219f2cf20',
    messagingSenderId: '1004167085921',
    projectId: 'pulchowkx-cb4e7',
    storageBucket: 'pulchowkx-cb4e7.firebasestorage.app',
    iosBundleId: 'com.example.pulchowkxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUO95owZ3EzkaziLVmFkZp5eMSEWxfstY',
    appId: '1:1004167085921:ios:4ad05d772ac02219f2cf20',
    messagingSenderId: '1004167085921',
    projectId: 'pulchowkx-cb4e7',
    storageBucket: 'pulchowkx-cb4e7.firebasestorage.app',
    iosBundleId: 'com.example.pulchowkxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBElsmr04m4H5GSg_ARLLmpgKFTgdA2jg0',
    appId: '1:1004167085921:web:d0637617133010f2f2cf20',
    messagingSenderId: '1004167085921',
    projectId: 'pulchowkx-cb4e7',
    authDomain: 'pulchowkx-cb4e7.firebaseapp.com',
    storageBucket: 'pulchowkx-cb4e7.firebasestorage.app',
    measurementId: 'G-3RRVHQ0J2L',
  );
}
